// Coin circuit breaker: every 5 minutes, compare each Zora coin's Uniswap v4 pool on Base
// (price + in-range liquidity) now vs. `lookbackBlocks` ago, and trip on abnormal moves.
// local-simulation mode only logs the decision; production mode writes a signed report
// to a CoinCircuitBreaker receiver that the flywheel checks before buying.
//
// CRE allows 15 EVM reads per execution, so pool state is read in batches straight from the
// PoolManager (`extsload`, 2 slots per coin) and pause status through Multicall3. The coin list
// is generated by scripts/sync-coins.ts; MAX_COINS keeps the worst case inside the read quota.
import {
  CronCapability,
  EVMClient,
  LAST_FINALIZED_BLOCK_NUMBER,
  Runner,
  TxStatus,
  blockNumber as toBlockNumber,
  bytesToHex,
  encodeCallMsg,
  getNetwork,
  handler,
  prepareReportRequest,
  protoBigIntToBigint,
  type Runtime,
} from "@chainlink/cre-sdk";
import {
  decodeFunctionResult,
  encodeAbiParameters,
  encodeFunctionData,
  isAddress,
  parseAbi,
  parseAbiParameters,
  zeroAddress,
  type Address,
  type Hex,
} from "viem";
import { z } from "zod";
import {
  chunk,
  coinIsCurrency0,
  coinPriceE18,
  decide,
  decodeLiquidity,
  decodeSlot0SqrtPrice,
  poolIdOf,
  poolStateSlots,
  reasonName,
  Reason,
  type Observation,
  type PoolKey,
} from "./breaker";

// CRE quota PerWorkflow.ChainRead.CallLimit is 15 and each read request must stay under 5 KB.
export const COINS_PER_EXTSLOAD = 60; // 2 slots x 32 B x 60 = 3.9 KB of calldata
export const PAUSE_CHECKS_PER_MULTICALL = 16; // ~224 B per aggregate3 entry = 3.6 KB
export const MAX_COINS = 120;
export const MAX_TRIPS_PER_REPORT = 25; // ~70k gas each; the rest go in the next run
export const readBudget = (coins: number, trips: number): number =>
  1 + 2 * Math.ceil(coins / COINS_PER_EXTSLOAD) + Math.ceil(trips / PAUSE_CHECKS_PER_MULTICALL);
if (readBudget(MAX_COINS, MAX_COINS) > 15) throw new Error("MAX_COINS exceeds the CRE EVM read quota");

const address = z.string().refine((v): boolean => isAddress(v, { strict: false }), "invalid address");
const uintString = z.string().regex(/^[1-9]\d*$/, "positive integer string");
const bps = z.number().int().min(1).max(10_000);

const coinSchema = z
  .object({
    symbol: z.string().min(1),
    address,
    poolKey: z
      .object({
        currency0: address,
        currency1: address,
        fee: z.number().int().min(0),
        tickSpacing: z.number().int(),
        hooks: address,
      })
      .strict(),
  })
  .strict();

const common = {
  schedule: z.string(),
  chainSelectorName: z.string(),
  poolManagerAddress: address,
  multicall3Address: address,
  lookbackBlocks: uintString,
  maxDropBps: bps,
  maxSpikeBps: bps,
  maxLiquidityDropBps: bps,
  coins: z.array(coinSchema).min(1).max(MAX_COINS),
};

export const configSchema = z.discriminatedUnion("mode", [
  z.object({ mode: z.literal("local-simulation"), ...common }).strict(),
  z
    .object({
      mode: z.literal("production"),
      ...common,
      breakerAddress: address.refine((v) => v.toLowerCase() !== zeroAddress, "breakerAddress must be nonzero"),
      gasLimit: uintString,
    })
    .strict(),
]);
export type Config = z.infer<typeof configSchema>;

const poolManagerAbi = parseAbi(["function extsload(bytes32[] slots) view returns (bytes32[])"]);
const multicall3Abi = parseAbi([
  "struct Call3 { address target; bool allowFailure; bytes callData; }",
  "struct Result { bool success; bytes returnData; }",
  "function aggregate3(Call3[] calls) payable returns (Result[] returnData)",
]);
const breakerAbi = parseAbi(["function isPaused(address coin) view returns (bool)"]);

type BlockRef = typeof LAST_FINALIZED_BLOCK_NUMBER | ReturnType<typeof toBlockNumber>;

const read = (runtime: Runtime<Config>, client: EVMClient, to: string, data: Hex, at: BlockRef): Hex =>
  bytesToHex(
    client
      .callContract(runtime, { call: encodeCallMsg({ from: zeroAddress, to: to as Address, data }), blockNumber: at })
      .result().data,
  );

/** Every coin's pool state at one block, COINS_PER_EXTSLOAD coins per EVM read. */
const observeAll = (runtime: Runtime<Config>, client: EVMClient, poolIds: Hex[], at: BlockRef): Observation[] =>
  chunk(poolIds, COINS_PER_EXTSLOAD).flatMap((ids) => {
    const slots = ids.flatMap(poolStateSlots);
    const data = read(runtime, client, runtime.config.poolManagerAddress, encodeFunctionData({ abi: poolManagerAbi, functionName: "extsload", args: [slots] }), at);
    const words = decodeFunctionResult({ abi: poolManagerAbi, functionName: "extsload", data });
    if (words.length !== slots.length) throw new Error(`extsload returned ${words.length} words for ${slots.length} slots`);
    return ids.map((_, i) => ({ sqrtPriceX96: decodeSlot0SqrtPrice(words[2 * i]), liquidity: decodeLiquidity(words[2 * i + 1]) }));
  });

/** Which of `coins` the breaker already has paused, PAUSE_CHECKS_PER_MULTICALL per EVM read. */
const pausedOf = (runtime: Runtime<Config>, client: EVMClient, breaker: Address, coins: Address[]): Set<string> => {
  const paused = new Set<string>();
  for (const batch of chunk(coins, PAUSE_CHECKS_PER_MULTICALL)) {
    const calls = batch.map((coin) => ({
      target: breaker,
      allowFailure: false,
      callData: encodeFunctionData({ abi: breakerAbi, functionName: "isPaused", args: [coin] }),
    }));
    const data = read(runtime, client, runtime.config.multicall3Address, encodeFunctionData({ abi: multicall3Abi, functionName: "aggregate3", args: [calls] }), LAST_FINALIZED_BLOCK_NUMBER);
    const results = decodeFunctionResult({ abi: multicall3Abi, functionName: "aggregate3", data });
    results.forEach((r, i) => {
      if (decodeFunctionResult({ abi: breakerAbi, functionName: "isPaused", data: r.returnData })) paused.add(batch[i].toLowerCase());
    });
  }
  return paused;
};

type CoinResult = {
  symbol: string;
  address: Address;
  reason: string;
  reasonCode: number;
  priceNowE18: string;
  priceChangeBps: string | null;
  liquidityThen: string;
  liquidityNow: string;
  liquidityChangeBps: string | null;
};

export const onCronTrigger = (runtime: Runtime<Config>): string => {
  const cfg = runtime.config;
  const network = getNetwork({ chainFamily: "evm", chainSelectorName: cfg.chainSelectorName });
  if (!network) throw new Error(`Unknown chain selector name: ${cfg.chainSelectorName}`);
  const client = new EVMClient(network.chainSelector.selector);

  // Anchor both observations to finalized blocks so every node reads identical state.
  const header = client.headerByNumber(runtime, { blockNumber: LAST_FINALIZED_BLOCK_NUMBER }).result().header;
  if (!header?.blockNumber) throw new Error("finalized header missing block number");
  const nowBlock = protoBigIntToBigint(header.blockNumber);
  const lookback = BigInt(cfg.lookbackBlocks);
  if (nowBlock <= lookback) throw new Error("chain shorter than lookback window");
  const thenBlock = nowBlock - lookback;
  runtime.log(`Comparing finalized block ${nowBlock} vs ${thenBlock} (${lookback} blocks back)`);

  const thresholds = {
    maxDropBps: BigInt(cfg.maxDropBps),
    maxSpikeBps: BigInt(cfg.maxSpikeBps),
    maxLiquidityDropBps: BigInt(cfg.maxLiquidityDropBps),
  };

  const keys = cfg.coins.map((coin) => coin.poolKey as PoolKey);
  const poolIds = keys.map(poolIdOf);
  const thenStates = observeAll(runtime, client, poolIds, toBlockNumber(thenBlock));
  const nowStates = observeAll(runtime, client, poolIds, toBlockNumber(nowBlock));

  const results: CoinResult[] = cfg.coins.map((coin, i) => {
    const addr = coin.address as Address;
    const then = thenStates[i];
    const now = nowStates[i];
    const d = decide(then, now, coinIsCurrency0(keys[i], addr), thresholds);
    const r: CoinResult = {
      symbol: coin.symbol,
      address: addr,
      reason: d.note ?? reasonName(d.reason),
      reasonCode: d.reason,
      priceNowE18: now.sqrtPriceX96 > 0n ? coinPriceE18(now.sqrtPriceX96, keys[i], addr).toString() : "0",
      priceChangeBps: d.priceChangeBps === null ? null : d.priceChangeBps.toString(),
      liquidityThen: then.liquidity.toString(),
      liquidityNow: now.liquidity.toString(),
      liquidityChangeBps: d.liquidityChangeBps === null ? null : d.liquidityChangeBps.toString(),
    };
    runtime.log(
      `${coin.symbol}: price ${r.priceChangeBps ?? "n/a"} bps, liquidity ${r.liquidityChangeBps ?? "n/a"} bps -> ${r.reason}`,
    );
    return r;
  });

  const tripped = results.filter((r) => r.reasonCode !== Reason.OK);

  if (cfg.mode === "local-simulation") {
    const out = {
      mode: "local-simulation",
      nowBlock: nowBlock.toString(),
      thenBlock: thenBlock.toString(),
      wouldTrip: tripped.map((r) => `${r.symbol}:${r.reason}`),
      coins: results,
    };
    runtime.log(`local-simulation: ${tripped.length} coin(s) would trip; no report built, nothing written`);
    return JSON.stringify(out);
  }

  // ─── production: one signed report pausing tripped coins that aren't paused yet ───
  // A coin that stays broken (e.g. zero liquidity) would otherwise be re-reported every run.
  const paused = tripped.length ? pausedOf(runtime, client, cfg.breakerAddress as Address, tripped.map((r) => r.address)) : new Set<string>();
  const toPause = tripped.filter((r) => !paused.has(r.address.toLowerCase())).slice(0, MAX_TRIPS_PER_REPORT);
  if (toPause.length === 0) {
    if (tripped.length) runtime.log(`${tripped.length} coin(s) tripped, all already paused; nothing to write`);
    return JSON.stringify({ mode: "production", tripped: tripped.map((r) => r.symbol), paused: [], txHash: null });
  }

  const observedAt = BigInt(runtime.now().getTime()) / 1000n;
  const encoded = encodeAbiParameters(parseAbiParameters("(address coin,uint8 reason,uint256 priceE18,uint256 observedAt)[]"), [
    toPause.map((r) => ({
      coin: r.address,
      reason: r.reasonCode,
      priceE18: BigInt(r.priceNowE18),
      observedAt,
    })),
  ]);
  const report = runtime.report(prepareReportRequest(encoded)).result();
  const write = client
    .writeReport(runtime, {
      receiver: cfg.breakerAddress,
      report,
      gasConfig: { gasLimit: cfg.gasLimit },
    })
    .result();
  if (write.txStatus !== TxStatus.SUCCESS) {
    throw new Error(write.errorMessage ?? `write status ${write.txStatus}`);
  }
  if (!write.txHash || write.txHash.length === 0) throw new Error("write succeeded without a transaction hash");
  const txHash = bytesToHex(write.txHash);
  runtime.log(`Breaker paused ${toPause.map((r) => r.symbol).join(", ")}; tx ${txHash}`);
  return JSON.stringify({ mode: "production", tripped: tripped.map((r) => r.symbol), paused: toPause.map((r) => r.symbol), txHash });
};

export const initWorkflow = (config: Config) => [
  handler(new CronCapability().trigger({ schedule: config.schedule }), onCronTrigger),
];

export async function main() {
  const runner = await Runner.newRunner<Config>({ configSchema });
  await runner.run(initWorkflow);
}
